### PR TITLE
New transaction model and optimizations

### PR DESCRIPTION
**Pull request by me-no-dev**
This PR implements a new transaction model for communication with ILI9341. Also uses some tricks to minimize pin changes and optimize code for more powerful SPI buses.

### CODE REVIEW

**Comment by ladyada** [comment]
getting some time to look at this now!

**Comment by me-no-dev** [comment]
We have one method that we want to add for drawing bitmaps, but I need to have a quick look at one of the ESP specific SPI methods. I'll look into that now with hope to get it merged along.

**Comment by ladyada** [comment]
ok please note that some functions were deleted (so far i have found pushColor() is gone and had to be re-added) can you let me know what other functions you deleted? that will help me greatly :) 

so far i have tested 328p and 32u4, will continue testing more platforms today :)

**Comment by ladyada** [comment]
ok all tested, seems good! i will hand-merge this and GFX
thank you @me-no-dev for the awesome code :)

**Comment by me-no-dev** [comment]
Great! Thanks for merging :) BTW I was not aware that I missed a method. I took special care not to but I guess I overlooked it somewhere :)

**Comment by ladyada** [comment]
all good! thx :)

**Pull request merged**
